import type { Metadata } from 'next';
import './globals.css';
import { Roboto } from 'next/font/google';
import css from './mainPage.module.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import QueryClientProviders from './QueryClientProviders';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  icons: {
    icon: '/logo.png',
  },
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <div className={css.gluedFooterContainer}>
          <QueryClientProviders>
            <Header />
            <main className={css.gluedFooterMain}>{children}</main>
            <Footer />
          </QueryClientProviders>
        </div>
      </body>
    </html>
  );
}
